version: '3.8'

services:
  frontend:
    image: dansil2301/tradex-frontend:latest
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: dansil2301/tradex:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      database:
        condition: service_healthy

  database:
    image: dansil2301/tradex-database:latest
    container_name: database
    ports:
      - "3390:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1NameDivision88
      - MYSQL_DATABASE=tradex_docker_dev_db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1NameDivision88" ]
      interval: 10s
      timeout: 5s
      retries: 3

